version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    restart: no
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - '5432'

  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  pg_data:
    external: false
