name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup Go 1.22.0
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'
          cache-dependency-path: go.sum
      - name: Setup CI Environment 
        if: ${{ steps.release.outputs.release_created }}
        run: |
          go install github.com/a-h/templ/cmd/templ@latest
          npm install -g tailwindcss
          npm install -D daisyui@latest
          tailwindcss -o assets/styles.css --minify
          templ generate
          go mod download
      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: CGO_ENABLED=0 GOOS=linux go build -o main cmd/main.go
      - name: Print Version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "New Version: v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
          echo "Release outputs: v${{ steps.release.outputs }} ${{ steps.release.outputs.tag_name }}"
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tar -cvzf cycling-coacl-lab.tar.gz main CHANGELOG.MD README.md LICENSE
          gh release upload ${{ steps.release.outputs.tag_name }} cycling-coach-app.tar.gz
      - name: Set up QEMU
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: PrepareReg Names
      #   id: read-docker-image-identifiers
      #   run: |
      #     echo VERSION_TAG=$(echo ${{ steps.version_step.outputs.version_tag }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      #     echo LASTEST_TAG=$(echo ${{ steps.version_step.outputs.latest_tag  }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: |
      #       ${{env.VERSION_TAG}}
      #       ${{env.LASTEST_TAG}}
      #     build-args: |
      #       ${{steps.version_step.outputs.version}}
