name: pull request
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.0
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'
          cache-dependency-path: go.sum
      - name: Setup CI Environment 
        run: |
          go install github.com/a-h/templ/cmd/templ@latest
          npm install -g tailwindcss
          npm install -D daisyui@latest
          tailwindcss -o assets/styles.css --minify
          templ generate
          go mod download
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -o main cmd/main.go
      - name: Run Unit Tests
        run: go test -race -cover ./...
      # - name: Upload Go test results
      #   uses: actions/upload-artifahttps://trello.com/c/kRAgyiZA/13-test-setup ct@v4
      #   with:
      #     name: Go-results
      #     path: TestResults.json

