name: pull request
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.0
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
          cache-dependency-path: src/go.sum
      - name: Setup CI Environment 
        run: |
          npm install
          npx tailwindcss -o assets/styles.css --minify
          go install github.com/a-h/templ/cmd/templ@latest
          templ generate -path src
          cd src; go mod download
      - name: Build
        run: |
          cd src; CGO_ENABLED=0 GOOS=linux go build -o main cmd/main.go
      - name: Run Tests
        uses: robherley/go-test-action@v0.1.0
        with:
          moduleDirectory: ./src
          omitUntestedPackages: true

  docker-build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: user/ap:latest
